### PR TITLE
Feature/default saving option

### PR DESCRIPTION
**Pull request by danielronnkvist**
When editing a user you can change your default identity, which in the future will be the default saving option.

### CODE REVIEW

**Comment by klaseskilson** [comment]
Wouldn't it be nice to add the default identity to the user model? So that we can use `user.default_identity` and get an `Identity` object?

Something like 

``` ruby
belongs_to :default_identity, class_name: "Identity"
```

Also, what happens if the identity that is the default identity gets removed?

**Comment by danielronnkvist** [comment]
Good point! I will look into it.

**Comment by klaseskilson** [comment]
Looks good!

**Comment by nattravn** [comment]
looks good

**Pull request merged**
