### PR TITLE
Empty strings isn't displayed as objects

### PR DESCRIPTION
**Pull request by danielronnkvist**
Moved the get values function into the jsTag file.

Fixes issue #37

### CODE REVIEW

**Comment by tkomstadius** [comment]
I still get empty tags with comma

**Comment by klaseskilson** [comment]
Me too!

**Comment by danielronnkvist** [comment]
The issue has been fixed.

**Comment by tkomstadius** [comment]
looks good

**Comment by klaseskilson** [comment]
Looks good, merging!

**Pull request merged**
