### PR TITLE
Feature/drive files

### PR DESCRIPTION
**Pull request by ronjagrosz**
With this feature you should be able to log in with your google account and browse your drive files, mark the files you want and save them.

### CODE REVIEW

**Comment by tkomstadius** [comment]
looks good

**Comment by danielronnkvist** [comment]
I think it looks good! There will be quite a conflict between this PR and PR #31. But if we merge this one to develop first, I can take care of the conflict since I'm the one changing the system :computer: :broken_heart:

**Comment by tkomstadius** [comment]
How do we get a Google docs file?

**Comment by tkomstadius** [comment]
Redirect to doc-url when clicking on a 'google-aps' file type

**Pull request merged**
