### PR TITLE
Feature/edit files

### PR DESCRIPTION
**Pull request by danielronnkvist**
Function for updating files!

### CODE REVIEW

**Comment by danielronnkvist** [comment]
If you would like to try it, paste this into the javascript console:

``` js
$.ajax({
  method: "PUT",
  url: "/files/update.json",
  dataType: "json",
  data: {
  bruse_file: {id: 1, name: "EINARS GOA"},
  tags: ["katttttt"]
}
});
```

**Comment by tkomstadius** [comment]
Should I copy and paste exactly that or should I change id and stuff?

**Comment by danielronnkvist** [comment]
It depends on which file you want to update.

**Comment by tkomstadius** [comment]
So I should be able to paste that exact copy? Because when I do I get a 404

**Comment by tkomstadius** [comment]
Yes, now I got a dog-pic with the tag kattttt. Very nice.

**Pull request merged**
