### PR TITLE
Feature/drive auth 2

### PR DESCRIPTION
**Pull request by ronjagrosz**
I don't know if it maybe should be merged with feature/modular-filehandling first. Anyways, I think the authentication with google is done. I don't know if it requires any testing?

PS. I created a new branch for drive-auth because I accidentally created the old one on top of filetag. Lesson learned, not much harm done. Should delete that branch. :smile:

### CODE REVIEW

**Comment by tkomstadius** [comment]
There are also merge conflicts

**Comment by ronjagrosz** [comment]
@tkomstadius the google/api_client is not necessary for authorization, although it is necessary for browsing the files which I am currently working on in feature/drive-files. So I should probably remove that code in this branch.

**Comment by klaseskilson** [comment]
Looks good!

**Comment by tkomstadius** [comment]
I think it looks good, just waiting for my google auth so I can add an account

**Comment by tkomstadius** [comment]
working! merging!

**Pull request merged**
