### PR TITLE
Feature/save drive dropbox on drop

### PR DESCRIPTION
**Pull request by danielronnkvist**
Files that are being dropped, uploaded through form or created from text box are being saved.

Restructured the upload method so that there is only one instead of two that does approximately the same thing. Files that are being uploaded from drag and drop are converted into a `Tempfile` to match the form upload. This was the solution that worked for google drive upload so I made it into a solution for every provider.

Also empties the JS array after a upload so that files already dropped are being uploaded again.

Error message isn't very stable. A loading indicator should be implemented so that users knows that something is happening.

:boom: :boom: :boom:

### CODE REVIEW

**Comment by klaseskilson** [comment]
Is

``` ruby
post '/upload_drop', to: 'upload#upload_from_base64', as: 'upload_drop'
```

in the routes actually used somewhere now?

**Comment by tkomstadius** [comment]
And do we need upload_from_base64.json.builder?

**Comment by tkomstadius** [comment]
I also get a problem when trying to save to Bruse; TypeError: "Cannot read property 'name' of undefined".
And it also printing a lot of info which is making it slower when saving to Bruse.

**Comment by klaseskilson** [comment]
Yes, `TypeError: Cannot read property 'name' of undefined at at DragDropCtrl.self-longhash.js?body=1:27` for me to when uploading to Bruse.

**Comment by danielronnkvist** [comment]
Forgot to delete unused stuff in other places than the upload controller. Will look into the error occurring when uploading to Bruse.

**Comment by klaseskilson** [comment]
Other than that, I say it looks good. Would be nice to make all the `upload_to_whatever` go away in some way, but I don't think we have time for that now. (Now it goes away from the idea that everything Identity-specific should be in the (super messy) Identity model.)

**Comment by tkomstadius** [comment]
I get this when trying to drop a link and save it: POST http://localhost:3000/upload.json  net::ERR_CONNECTION_REFUSED

**Comment by tkomstadius** [comment]
Höhöh min server va inte på. Det funkar nu och ser fint ut. :traffic_light:

**Comment by tkomstadius** [comment]
Push the button :radio_button:

**Comment by klaseskilson** [comment]
Waaaait! The `gem 'certified'` business in Gemfile. Where are we on that? Is it needed?

**Comment by klaseskilson** [comment]
Error when uploading to Drive:

```
NoMethodError at /upload.json
=============================

> undefined method `[]' for nil:NilClass

 () Users/kalas/dev/bruse/app/controllers/files/upload_controller.rb, line 148
------------------------------------------------------------------------------

ruby
  143       # returns BruseFile parameters
  144       def upload_to_google
  145         response = @identity.upload_to_google(@file)
  146         @file = BruseFile.new(
  147           name: @file.original_filename,
> 148           foreign_ref: response["id"],
  149           filetype: response["mimeType"],
  150           identity: @identity
  151         )
  152       end
  153   end


App backtrace
-------------

 -  () Users/kalas/dev/bruse/app/controllers/files/upload_controller.rb:148:in `upload_to_google'
 -  () Users/kalas/dev/bruse/app/controllers/files/upload_controller.rb:38:in `upload'
```

**Comment by klaseskilson** [comment]
Ok, that's probably only something local for me. Go ahead!

**Comment by klaseskilson** [comment]
(But it's something that needs to be handled by the system, I think.)

**Comment by klaseskilson** [comment]
Everything's green! 👌

**Pull request merged**
