### PR TITLE
Feature/create password

### PR DESCRIPTION
**Pull request by danielronnkvist**
A user without a password can create one. An email will be sent to the user with a unique create password link.

Unfortunately if a user is signed in when doing this the user will be logged out.

Only users without a password have the ability to access the needed pages.

### CODE REVIEW

**Comment by ronjagrosz** [comment]
Looks good! I see no problem with getting logged out when changing password.

**Comment by tkomstadius** [comment]
Looks good. But perhaps we should have a link to "forgot password" from the inside as well?

**Comment by ronjagrosz** [comment]
"You can also request a reset password email while signed in" I can't seem to find this. Should it be in settings? Or are you still implementing this?

**Comment by danielronnkvist** [comment]
We don't link to the edit user page. But if you visit `/users/edit` you will find it.

**Pull request merged**
