### PR TITLE
Feature/tag button after drop

### PR DESCRIPTION
**Pull request by tkomstadius**
Removed picture preview, show saved files in list using template. Maybe not  ths prettiest solution but it works now.

### CODE REVIEW

**Comment by tkomstadius** [comment]
This does not work!

**Comment by tkomstadius** [comment]
Should be ok now. :sake:

**Comment by klaseskilson** [comment]
I couldn't add tags! I got the following error in the browser console:

```
TypeError: Cannot read property 'getTagValues' of undefined
```

It appears as if the `JsTagCollection` object isn't added properly. I might have a solution, will push in a couple of minutes.

**Comment by tkomstadius** [comment]
oh dammit :crying_cat_face:

**Comment by klaseskilson** [comment]
Progress! New error though: `TypeError: file.unsavedTags.getTagValues is not a function`. 💩

Looking into it.

**Comment by klaseskilson** [comment]
That might be it! :tractor:

**Comment by klaseskilson** [comment]
I'm not sure why it isn't working for you now, @tkomstadius. Images, links and everything else is working for me. What error do you get?

**Comment by klaseskilson** [comment]
Looks good to me! It would be great if we could get some fresh eyes on this. ⭐️

**Comment by ronjagrosz** [comment]
Is this part of the "fulfix"? That it is duplicate after you have chosen where to upload.
tag-button-after-drop

**Comment by ronjagrosz** [comment]
Other than that it looks good! :dog:

**Comment by nattravn** [comment]
It's works good, I merge it

**Pull request merged**
