### PR TITLE
Feature/delay trigrams

### PR DESCRIPTION
**Pull request by danielronnkvist**
#### before

before
#### after

after

### CODE REVIEW

**Comment by ronjagrosz** [comment]
:clock1: :+1:

**Comment by danielronnkvist** [comment]
Hold your :horse: :horse_racing: on this one, I'm not sure they really are being created...

**Comment by danielronnkvist** [comment]
So heres the deal, to handle the background jobs another process has to be running. So in a new terminal window run `rake jobs:work`to start that process. I created a Procfile which tells a process manager like [Foreman](http://theforeman.org/) to run both processes on the command `foreman start` if you don't want to have two different windows.

**Comment by klaseskilson** [comment]
Cool! 😎Maby you could update the readme with this information?

**Pull request merged**
